### ISSUE TITLE
Implementation with Lock

### ISSUE THREAD

**Issue by iboxgithub** [optune/meteor-auth0-oauth#1]
Hi (newbie over here), sorry to raise an issue as it is more of a question: I don't understand how to link your code to lock (in React Native)
From what I understood
- auth0_server is used to manage the user creation within Meteor user account 
- auth0_client is used to provide a Front end endpoint for a client to connect (like Lock) --> is it correct?

So now I use Lock with this code...
```
const lock = new Auth0Lock({clientId: 'xx', domain: 'xx.auth0.com'},
    {
        auth:{
            redirectUrl: 'http://192.168.0.12:3000/_oauth/auth0',
            responseType: 'code',
            params: {
                scope: 'openid email' // Learn about scopes: https://auth0.com/docs/scopes
            }
        }
    });
```
...but even though the Auth0 connection works great I don't create my user in Meteor backend :(
I don't know if my **redirectUrl** is good nor if my **params** are good...

Can you give me a hint on how to do that?

Thanks for your help

**Comment by schmidsi** [comment]
Hi there,

Unfortunately, it is currently not possible to use the Auth0 Lock with this module. It is a simple OAuth2.0 wrapper. Meteor has it's own way of creating and authorising users and I did not find time to dig deep into it. That said, OAuth2.0 standard flow works fine, as you can see on http://optune.me.

Feel free to investigate this issue on your own and make a pull request.

**Comment by iboxgithub** [comment]
thanks
