### ISSUE TITLE
Package doesn't exist

### ISSUE THREAD

**Issue by purplecones** [optune/meteor-auth0-oauth#2]
Hi, I'm trying to use this meteor package but it doesn't seem to be available.

```
$ meteor add optune:auth0-oauth
 => Errors while parsing arguments:

While adding package optune:auth0-oauth:
error: no such package
```

Is there a different name for it?

**Comment by shankscoder** [comment]
Updating this for sake of consistency.

You need to clone this repo and place it in a `packages` folder in your folder root.

Then you can add the package. Meteor scans that folder for any custom/local packages you might have created before it hits Atmosphere.
